apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: test-subscription
  namespace: {{ TNF_EXAMPLE_CNF_NAMESPACE }}  
spec:
  channel: production 
  name: redis-enterprise-operator-cert
  source: test-catalog 
  sourceNamespace: {{ CATALOG_NAMESPACE }} 
