---
apiVersion: v1
kind: Namespace
metadata:
  name: test2
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: test2
  name: testadmin
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: testadminbinding
  namespace: test2
subjects:
  - kind: ServiceAccount
    name: test-pod-sa
    namespace: tnf
    apiGroup: ""
roleRef:
  kind: Role
  name: testadmin
  apiGroup: ""
